cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.CartDetail, name='CartDetail'),
    url(r'^remove/(?P<product_id>\d+)/$', views.CartRemove, name='CartRemove'),
    url(r'^add/(?P<product_id>\d+)/$', views.CartAdd, name='CartAdd'),
]

core_shop/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_view
from . import views

urlpatterns = [
    url(r'^customer_products/$', views.customer_products, name='customer_products'),
    url(r'^$', views.product_list, name='product_list'),
    url(r'^filter/$', views.product_list_f, name = 'product_filter'),
    url(r'^login/$', auth_view.login, { 'template_name' : 'shop/login.html'}, name='login'),
    url(r'^logout/$', auth_view.logout, { 'next_page' : '/'  }, name='logout'),
    url(r'^product/new/$', views.product_new, name='product_new'),
    url(r'^product/(?P<id>\d+)/(?P<slug>[-\w]+)/edit/$', views.product_edit, name='product_edit'),
    url(r'^product/(?P<id>\d+)/(?P<slug>[-\w]+)/delete/$', views.product_delete, name='product_delete'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
]

darknet_shop/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^order/', include('orders.urls', namespace='orders')),
    url(r'^', include('core_shop.urls', namespace='core_shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^create/$', views.OrderCreate, name='OrderCreate')
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int, label='Количество')
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from core_shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm

@require_POST
def CartAdd(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        # remove products from stock
        count = cd['quantity']
        # if product count is invalid
        if count > product.count:
            # buy all products
            cart.add(product=product, quantity=product.count,
                     update_quantity=cd['update'])
            product.change_count(-product.count)
        else:
            cart.add(product=product, quantity=cd['quantity'],
                     update_quantity=cd['update'])
            product.change_count(-cd['quantity'])
    return redirect('cart:CartDetail')

def CartRemove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:CartDetail')

def CartDetail(request):
    if not request.user.is_authenticated:
        return redirect('/')
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
                                        initial={
                                            'quantity': item['quantity'],
                                            'update': True
                                        })
    return render(request, 'cart/detail.html',
                 {'cart': cart})

cart/templates/cart/detail.html
{% extends 'shop/base.html' %}
{% load static %}

{% block title %}
Корзина
{% endblock %}

{% block content %}
<h1>Корзина</h1>
<table class="table table-cart table-condensed">
	<thead>
		<tr>
			<th>Изображение</th>
			<th>Продукт</th>
			<th>Количество</th>
			<th>Удалить</th>
			<th>Полная цена</th>
			<th>Цена</th>
		</tr>
	</thead>
	<tbody>
		{% for item in cart %}
		{% with product=item.product %}
		<tr>
			<td class = "cart-img">
				<a href="{{ product.get_absolute_url }}">
					<img src="{{ product.image.url }}" alt="" class = "img-responsive"/>
				</a>
			</td>
			<td>{{ product.name }}</td>
			<td>{{ item.quantity }}</td>
			<td><a href="{% url "cart:CartRemove" product.id %}">Удалить</a></td>
			<td class="num">{{ item.price }} руб.</td>
			<td class="num">{{ item.total_price }} руб.</td>
		</tr>
		{% endwith %}
		{% endfor %}
		<tr class="price">
			<td colspan = "2">Общая сумма заказа</td>
			<td colspan="3"></td>
			<td class="num">{{ cart.get_total_price }} руб.</td>
		</tr>
	</tbody>
</table>
<p class="text-right">
<a href="{% url "core_shop:product_list"%}" class="btn btn-default">Вернуться к товарам</a>
{% if cart.get_total_price > 0 %}
<a href="{% url "orders:OrderCreate" %}" class = "btn btn-success">Оформить заказ</a>
{% endif %}
</p>
{% endblock %}