cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.CartDetail, name='CartDetail'),
    url(r'^remove/(?P<product_id>\d+)/$', views.CartRemove, name='CartRemove'),
    url(r'^add/(?P<product_id>\d+)/$', views.CartAdd, name='CartAdd'),
]

core_shop/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_view
from . import views

urlpatterns = [
    url(r'^customer_products/$', views.customer_products, name='customer_products'),
    url(r'^$', views.product_list, name='product_list'),
    url(r'^filter/$', views.product_list_f, name = 'product_filter'),
    url(r'^login/$', auth_view.login, { 'template_name' : 'shop/login.html'}, name='login'),
    url(r'^logout/$', auth_view.logout, { 'next_page' : '/'  }, name='logout'),
    url(r'^product/new/$', views.product_new, name='product_new'),
    url(r'^product/(?P<id>\d+)/(?P<slug>[-\w]+)/edit/$', views.product_edit, name='product_edit'),
    url(r'^product/(?P<id>\d+)/(?P<slug>[-\w]+)/delete/$', views.product_delete, name='product_delete'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
]

darknet_shop/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^order/', include('orders.urls', namespace='orders')),
    url(r'^', include('core_shop.urls', namespace='core_shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core_shop/models.py
# coding: utf-8
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

class Category(models.Model):
    name = models.CharField(max_length=50, verbose_name='Категория')
    slug = models.SlugField(max_length=50, unique=True, help_text='Уникальное значение для URL категории')
    description = models.TextField(max_length = 2000)
    is_active = models.BooleanField(default = True)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

    class Meta:
        db_table = 'categories'
        ordering = ['name']
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __unicode__(self):
        return self.name

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('core_shop:product_list_by_category', args=[self.slug])


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    customer = models.BooleanField(default=False)
    # cart = models.ForeignKey(CartItem, related_name='Корзина', verbose_name="Корзина", null=True)
    def __str__(self):
        return "Продавец" if self.customer else "Покупатель"

@receiver(post_save, sender = User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user = instance)

@receiver(post_save, sender = User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

class Product(models.Model):
    category = models.ForeignKey(Category, related_name='Категория', verbose_name="Категория")
    name = models.CharField(max_length=255, unique=True, verbose_name="Название")
    brand = models.CharField(max_length = 50, verbose_name="Производитель")
    image = models.ImageField(upload_to='product/%Y/%m/%d', default = '/default/no-img.png', blank = True, verbose_name='Изображение')
    slug = models.SlugField(max_length=255, unique=True, help_text='Уникальное значение для ULR продукта')
    description = models.TextField(blank=True, verbose_name="Описание")
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Цена")
    count = models.PositiveIntegerField(verbose_name="Количество на складе")
    available = models.BooleanField(default=True, verbose_name="Доступен")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    profile = models.ForeignKey(Profile, null=True,  related_name='Профиль')

    class Meta:
        db_table = 'products'
        ordering = ['name']
        index_together = [['id', 'slug']]
        verbose_name = "Продукт"
        verbose_name_plural = "Продукты"

    def __unicode__(self):
        return self.name

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('core_shop:product_detail', args=[self.id, self.slug])

    def change_count(self, count):
        self.count += int(count)
        self.available = self.count > 0
        self.save()

core_shop/forms.py
from django import forms
from .models import Category, Product
import django_filters

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ('name', 'brand', 'category','image', 'price', 'description', 'available', 'count',  )

class ProductDeleteForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ()

class ProductFilter(django_filters.FilterSet):
    name = django_filters.CharFilter(lookup_expr='icontains', label = 'Название содержит')
    # price = django_filters.NumberFilter()
    price__gt = django_filters.NumberFilter(name='price', lookup_expr='gt', label = 'Цена более')
    price__lt = django_filters.NumberFilter(name='price', lookup_expr='lt', label = 'Цена менее')
    class Meta:
        model = Product
        fields = ( 'category',  )

class ProductBuyForm(forms.Form):
    count = forms.IntegerField(label='Количество товара', initial=1, min_value=1)
    class Meta:
        model = Product
        fields = ('count',)

core_shop/views.py
import unidecode
from unidecode import unidecode
from django.shortcuts import render, get_object_or_404, redirect
from .models import Category, Product
from .forms import ProductForm, ProductDeleteForm, ProductFilter
from cart.forms import CartAddProductForm
from django.utils import timezone
from django.utils.text import slugify

def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request, 'shop/product/list.html', {
        'category': category, 'categories': categories, 'products': products})

#Фильтр продуктов
def product_list_f(request):
    f = ProductFilter(request.GET, queryset = Product.objects.all())
    return render(request, 'shop/product/filter.html', { 'filter' : f })

def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug)
    cart_product_form = CartAddProductForm()
    return render(request, 'shop/product/detail.html',
                             {'product': product,
                              'cart_product_form': cart_product_form})


def is_customer(request):
    if request.Profile.user.is_authenticated():
        current_user = request.Profile
        if current_user.customer:
            return True
        else:
            return False
    else:
        return False

def product_new(request):
    if not request.user.profile.customer:
        return redirect('/')
    if request.method == "POST":
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save(commit = False)
            product.created_at = timezone.now()
            product.updated_at = timezone.now()
            product.slug = slugify(unidecode(product.name))
            product.profile = request.user.profile
            product.save()
            # return render(request, 'shop.views.product_detail',{'id': product.id, 'slug':product.slug})
            return redirect('/')
    else:
        form = ProductForm()
        return render(request, 'shop/product/product_edit.html', {'form' : form})

def product_edit(request, id, slug):
    product = get_object_or_404(Product, id = id, slug = slug)
    if request.user != product.profile.user or not request.user.is_authenticated:
        return redirect('/')
    if request.method == "POST":
        form = ProductForm(request.POST, request.FILES, instance = product)
        if form.is_valid():
            product = form.save(commit = False)
            product.created_at = timezone.now()
            product.updated_at = timezone.now()
            product.slug = slugify(unidecode(product.name))
            product.save()
            # return redirect('shop.views.product_detail', id = product.id, slug = product.slug)
            # return render(request, 'shop.views.product_detail',{'id': product.id, 'slug':product.slug})
            return redirect('/')
    else:
        form = ProductForm(instance = product)
        return render(request, 'shop/product/product_edit.html', {'form' : form})

def product_delete(request, id, slug):
    product_to_delete = get_object_or_404(Product, id = id, slug = slug)
    if request.user != product_to_delete.profile.user or not request.user.is_authenticated:
        return redirect('/')
    if request.method == "POST":
        form = ProductDeleteForm(request.POST, instance = product_to_delete)
        if form.is_valid():
            product_to_delete.delete()
            return redirect('/')
    else:
        form = ProductDeleteForm(instance = product_to_delete)
    return render(request, 'shop/product/product_delete.html', {'form' : form, 'product' : product_to_delete})

def customer_products(request):
    if not request.user.profile.customer or not request.user.is_authenticated:
        return redirect('/')
    # get customer's products
    products = Product.objects.filter(profile=request.user.profile)
    return render(request, 'shop/product/customer_products.html',
                  {'products': products})

core_shop/templates/shop/product/customer_products.html
{% extends 'shop/base.html' %}

{% block title %}
Ваши товары
{% endblock %}

{% block content %}
    <h1>Ваши товары</h1>
    {% if products.count > 0 %}
        <table class="table table-cart table-condensed">
            <thead>
                <tr>
                    <th>Изображение</th>
                    <th>Продукт</th>
                    <th>Категория</th>
                    <th>Количество</th>
                    <th>Цена</th>
                    <th>Редактировать</th>
                    <th>Удалить</th>
                </tr>
            </thead>
            <tbody>
                {% for product in products %}
                <tr>
                    <td class = "cart-img">
                        <a href="{{ product.get_absolute_url }}">
                            <img src="{{ product.image.url }}" alt="" class = "img-responsive"/>
                        </a>
                    </td>
                    <td>{{ product.name }}</td>
                    <td>{{ product.category }}</td>
                    <td>{{ product.count }}</td>
                    <td class="num">{{ product.price }} руб.</td>
                    <td><a href="{% url 'core_shop:product_edit' id=product.id slug=product.slug  %}">Редактировать</a></td>
                    <td><a href="{% url 'core_shop:product_delete' id=product.id slug=product.slug  %}">Удалить</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <p class="text-right">
        <a href="{% url "core_shop:product_list"%}" class="btn btn-default">Вернуться к товарам</a></p>
    {% else %}
        <p>Вы не добавили ни одного товара.</p>
    {% endif %}
{% endblock %}

core_shop/templates/shop/product/detail.html
{% extends 'shop/base.html' %}
{% load static %}
{% block title %}{{ product.name }}{% endblock %}

{% block content %}
<div class="product-detail">
	<div class="col-sm-4">
		<img class = "img-rounded img-responsive" src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no-image.jpg"%}{% endif %}" class="cart-img">
	</div>
	<div class="col-sm-8">
		<h1>{{ product.name }}</h1>
		<div class = "panel panel-primary">
			<div class = "panel-heading"><b>Описание</b></div>
			<div class = "panel-body">
				<b>Производитель: </b> {{ product.brand }}
				<br>
				<b>Категория: </b><a href="{{ product.category.get_absolute_url }}">{{ product.category.name }}</a>
				<hr>
				<p class="price"><b>Цена: </b> {{ product.price }} руб.</p>
				<hr>
				<span>{{ product.description | linebreaks }}</span>
				<hr>
				{% if user.is_authenticated and product.available %}
				<form action="{% url "cart:CartAdd" product.id %}" method="post">
					{{ cart_product_form }}
					{% csrf_token %}
					<input type="submit" value="Добавить в корзину">
				</form>
				{% endif %}
			</div>
		</div>
	</div>
</div>
{% endblock %}

core_shop/templates/shop/product/filter.html
{% extends "shop/base.html" %}

{% block title %}
Поиск
{% endblock %}

{% block content %}
	<form action="" method="get">
		{{ filter.form.as_p }}
		<button type = "submit" class = "save btn btn-default">Поиск</button>
	</form>
		<h1>Товары</h1>
		<div class="items_row">
			{% for obj in filter.qs %}
			<div class="item col-sm-4">
				<a href="{{ obj.get_absolute_url }}">{{ obj.name }}</a><br>
				{{ obj.price }} руб.
			</div>
			{% endfor %}
		</div>
	{% endblock %}

core_shop/templates/shop/product/list.html
{% extends 'shop/base.html' %}
{% load static %}

{% block title %}
    {% if category %}{{ category.name }}{% else %} Страница товаров {% endif %}
{% endblock %}


{% block content %}
<div class="row">
<div class="col-sm-3">
	<div class="panel panel-default">
		<div class="panel-heading">Категории</div>
		<div class="panel-body">
			<ul class = "nav nav-pills nav-stacked">
				<li {% if not category %} class="active" {% endif %}>
				<a href="{% url "core_shop:product_list" %}">Все</a>
				</li>
				{% for cat in categories %}
				<li {% if category.slug == cat.slug %} class="active" {% endif %}>
				<a href="{{ cat.get_absolute_url }}">{{ cat.name }}</a>
				</li>
				{% endfor %}
			</ul>
		</div>
	</div>
</div>
<div class="col-sm-9">
	<h1>{% if category %}{{ category.name }}{% else %}Товары{% endif %}</h1>
	<div class="items row">
		{% for product in products %}
		<div class="item col-sm-4">
			{% if product.available %}<br>
			<a href="{{ product.get_absolute_url }}"><img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no-image.jpg"%}{% endif %}" class="list-img"></a>
			<br>
			<a href="{{ product.get_absolute_url }}">{{ product.name }}</a><br>
			{{ product.price }} руб.
			{% endif %}
		</div>
		{% endfor %}
	</div>
</div>
</div>
{% endblock %}

core_shop/templates/shop/product/product_delete.html
{% extends 'shop/base.html' %}
{% load static %}
{% block title %}
Удаление товара
{% endblock %}

{% block content %}
	<h1>Вы действительно хотите удалить "{{ product.name }}"?</h1>
	<form method = "POST" class = "post-form">{% csrf_token %}
		{{ form.as_p  }}
		<button type = "submit" class = "save btn btn-default">Удалить</button>
	<a href="{% url "core_shop:product_list"%}" class="btn btn-default">Вернуться к товарам</a>
	</form>
{% endblock %}

core_shop/templates/shop/product/product_edit.html
{% extends 'shop/base.html' %}
{% load static %}
{% block title %}
{% if request.resolver_match.url_name == "product_edit" %}
Редактирование товара
{% else %}
Добавление товара
{% endif %}
{% endblock %}

{% block content %}
<div class = "row">
<form method = "POST" class = "post-form" enctype="multipart/form-data">{% csrf_token %}
{{ form.as_p  }}
<button type = "submit" class = "save btn btn-default">Сохранить</button>
</form>
</div>
{% endblock %}