cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.CartDetail, name='CartDetail'),
    url(r'^remove/(?P<product_id>\d+)/$', views.CartRemove, name='CartRemove'),
    url(r'^add/(?P<product_id>\d+)/$', views.CartAdd, name='CartAdd'),
]

core_shop/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_view
from . import views

urlpatterns = [
    url(r'^customer_products/$', views.customer_products, name='customer_products'),
    url(r'^$', views.product_list, name='product_list'),
    url(r'^filter/$', views.product_list_f, name = 'product_filter'),
    url(r'^login/$', auth_view.login, { 'template_name' : 'shop/login.html'}, name='login'),
    url(r'^logout/$', auth_view.logout, { 'next_page' : '/'  }, name='logout'),
    url(r'^product/new/$', views.product_new, name='product_new'),
    url(r'^product/(?P<id>\d+)/(?P<slug>[-\w]+)/edit/$', views.product_edit, name='product_edit'),
    url(r'^product/(?P<id>\d+)/(?P<slug>[-\w]+)/delete/$', views.product_delete, name='product_delete'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
]

darknet_shop/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^order/', include('orders.urls', namespace='orders')),
    url(r'^', include('core_shop.urls', namespace='core_shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core_shop/models.py
# coding: utf-8
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

class Category(models.Model):
    name = models.CharField(max_length=50, verbose_name='Категория')
    slug = models.SlugField(max_length=50, unique=True, help_text='Уникальное значение для URL категории')
    description = models.TextField(max_length = 2000)
    is_active = models.BooleanField(default = True)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

    class Meta:
        db_table = 'categories'
        ordering = ['name']
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __unicode__(self):
        return self.name

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('core_shop:product_list_by_category', args=[self.slug])


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    customer = models.BooleanField(default=False)
    # cart = models.ForeignKey(CartItem, related_name='Корзина', verbose_name="Корзина", null=True)
    def __str__(self):
        return "Продавец" if self.customer else "Покупатель"

@receiver(post_save, sender = User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user = instance)

@receiver(post_save, sender = User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

class Product(models.Model):
    category = models.ForeignKey(Category, related_name='Категория', verbose_name="Категория")
    name = models.CharField(max_length=255, unique=True, verbose_name="Название")
    brand = models.CharField(max_length = 50, verbose_name="Производитель")
    image = models.ImageField(upload_to='product/%Y/%m/%d', default = '/default/no-img.png', blank = True, verbose_name='Изображение')
    slug = models.SlugField(max_length=255, unique=True, help_text='Уникальное значение для ULR продукта')
    description = models.TextField(blank=True, verbose_name="Описание")
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Цена")
    count = models.PositiveIntegerField(verbose_name="Количество на складе")
    available = models.BooleanField(default=True, verbose_name="Доступен")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    profile = models.ForeignKey(Profile, null=True,  related_name='Профиль')

    class Meta:
        db_table = 'products'
        ordering = ['name']
        index_together = [['id', 'slug']]
        verbose_name = "Продукт"
        verbose_name_plural = "Продукты"

    def __unicode__(self):
        return self.name

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('core_shop:product_detail', args=[self.id, self.slug])

    def change_count(self, count):
        self.count += int(count)
        self.available = self.count > 0
        self.save()

core_shop/forms.py
from django import forms
from .models import Category, Product
import django_filters

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ('name', 'brand', 'category','image', 'price', 'description', 'available', 'count',  )

class ProductDeleteForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ()

class ProductFilter(django_filters.FilterSet):
    name = django_filters.CharFilter(lookup_expr='icontains', label = 'Название содержит')
    # price = django_filters.NumberFilter()
    price__gt = django_filters.NumberFilter(name='price', lookup_expr='gt', label = 'Цена более')
    price__lt = django_filters.NumberFilter(name='price', lookup_expr='lt', label = 'Цена менее')
    class Meta:
        model = Product
        fields = ( 'category',  )

class ProductBuyForm(forms.Form):
    count = forms.IntegerField(label='Количество товара', initial=1, min_value=1)
    class Meta:
        model = Product
        fields = ('count',)

core_shop/views.py
import unidecode
from unidecode import unidecode
from django.shortcuts import render, get_object_or_404, redirect
from .models import Category, Product
from .forms import ProductForm, ProductDeleteForm, ProductFilter
from cart.forms import CartAddProductForm
from django.utils import timezone
from django.utils.text import slugify

def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request, 'shop/product/list.html', {
        'category': category, 'categories': categories, 'products': products})

#Фильтр продуктов
def product_list_f(request):
    f = ProductFilter(request.GET, queryset = Product.objects.all())
    return render(request, 'shop/product/filter.html', { 'filter' : f })

def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug)
    cart_product_form = CartAddProductForm()
    return render(request, 'shop/product/detail.html',
                             {'product': product,
                              'cart_product_form': cart_product_form})


def is_customer(request):
    if request.Profile.user.is_authenticated():
        current_user = request.Profile
        if current_user.customer:
            return True
        else:
            return False
    else:
        return False

def product_new(request):
    if not request.user.profile.customer:
        return redirect('/')
    if request.method == "POST":
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save(commit = False)
            product.created_at = timezone.now()
            product.updated_at = timezone.now()
            product.slug = slugify(unidecode(product.name))
            product.profile = request.user.profile
            product.save()
            # return render(request, 'shop.views.product_detail',{'id': product.id, 'slug':product.slug})
            return redirect('/')
    else:
        form = ProductForm()
        return render(request, 'shop/product/product_edit.html', {'form' : form})

def product_edit(request, id, slug):
    product = get_object_or_404(Product, id = id, slug = slug)
    if request.user != product.profile.user or not request.user.is_authenticated:
        return redirect('/')
    if request.method == "POST":
        form = ProductForm(request.POST, request.FILES, instance = product)
        if form.is_valid():
            product = form.save(commit = False)
            product.created_at = timezone.now()
            product.updated_at = timezone.now()
            product.slug = slugify(unidecode(product.name))
            product.save()
            # return redirect('shop.views.product_detail', id = product.id, slug = product.slug)
            # return render(request, 'shop.views.product_detail',{'id': product.id, 'slug':product.slug})
            return redirect('/')
    else:
        form = ProductForm(instance = product)
        return render(request, 'shop/product/product_edit.html', {'form' : form})

def product_delete(request, id, slug):
    product_to_delete = get_object_or_404(Product, id = id, slug = slug)
    if request.user != product_to_delete.profile.user or not request.user.is_authenticated:
        return redirect('/')
    if request.method == "POST":
        form = ProductDeleteForm(request.POST, instance = product_to_delete)
        if form.is_valid():
            product_to_delete.delete()
            return redirect('/')
    else:
        form = ProductDeleteForm(instance = product_to_delete)
    return render(request, 'shop/product/product_delete.html', {'form' : form, 'product' : product_to_delete})

def customer_products(request):
    if not request.user.profile.customer or not request.user.is_authenticated:
        return redirect('/')
    # get customer's products
    products = Product.objects.filter(profile=request.user.profile)
    return render(request, 'shop/product/customer_products.html',
                  {'products': products})

core_shop/templates/shop/base.html
{% load static %}
{% load tags %}

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>{% block title %}{% endblock %}</title>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	<link rel="stylesheet" href="{% static "css/style.css" %}">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<link rel="stylesheet" href="{% static "css/style.css" %}">
</head>
<body>
{% block nav %}
<nav class="navbar navbar-inverse">
	<div class="navbar-header">
		<a class="navbar-brand" href="/">DarkNet Shop</a>
	</div>
	<div id="navbarCollapse" class="collapse navbar-collapse">
		<ul class="nav navbar-nav">
			<li class="{% if request.resolver_match.url_name == "product_list" %}active{% endif %}"><a href="/"><span class="glyphicon glyphicon-home"></span> Домой</a></li>
			<!-- <li class=dropdown> -->
			<!-- 	<a class="dropdown-toggle" data-toggle="dropdown" href="#"><span class="glyphicon glyphicon-list-alt"></span> Категории<span class="caret"></span></a> -->
			<!-- 	<ul class="dropdown-menu"> -->
			<!-- 		<li><a href="#">Page 1-1</a></li> -->
			<!-- 		<li><a href="#">Page 1-2</a></li> -->
			<!-- 		<li><a href="#">Page 1-3</a></li> -->
			<!-- 	</ul> -->
			<!-- </li> -->
			<li class="{% if request.resolver_match.url_name == "product_filter" %}active{% endif %}"><a href="/filter"><span class = "glyphicon glyphicon-search"></span> Поиск</a></li>
		</ul>
		<ul class="nav navbar-nav navbar-right">
			{% with total_items=cart|length %}
			{% if user.is_authenticated %}
			<li class="{% if request.resolver_match.url_name == "CartDetail" %}active{% endif %}"><a href="{% url 'cart:CartDetail' %}"><span class="glyphicon glyphicon-shopping-cart"></span> Корзина <span class="badge">{{ total_items  }}</span></a></li>
			<li class = dropdown>
				<a class="dropdown-toggle" data-toggle="dropdown" href="#"><span class='glyphicon glyphicon-user'></span> Привет, {{ user.username  }}</a>
				<ul class = "dropdown-menu">
				{% if user.profile.customer %}
				<li class="{% if request.resolver_match.url_name == "product_new" %}active{% endif %}"><a href="{% url 'core_shop:product_new' %}"><span class = "glyphicon glyphicon-plus"></span> Добавить товар</a></li>
                <li class="{% if request.resolver_match.url_name == "customer_products" %}active{% endif %}"><a href="{% url 'core_shop:customer_products' %}"><span class = "glyphicon glyphicon-th-list"></span> Просмотр товаров</a></li>
				{% endif %}
				<li><a href="/logout"><span class='glyphicon glyphicon-log-out'></span> Выйти</a></li>
				</ul>
			</li>
			{% else  %}
			<li><a href="/login"><span class="glyphicon glyphicon-log-in"></span> Войти</a></li>
			{% endif %}
			{% endwith %}
		</ul>
	</div>
</nav>
{% endblock  %}
<section id="content row" class="container">
	{% block content %}{% endblock %}
</section>
</body>
</html>

core_shop/templates/shop/login.html
{% extends 'shop/base.html' %}

{% block title %}Вход{% endblock %}

{% block content %}
<h2>Авторизация</h2>
<form method="post">
	{% csrf_token %}
	{{ form.as_p }}
	<button type="submit">Войти</button>
</form>
{% endblock %}